import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // This is the function that will be called when the button is clicked
  const handleGetMongoDoc = () => {
    console.log("get mongo doc");
    fetch("/api/get-mongo-doc") // This is the route we created in the previous step
      .then((response) => response.json())
      .then((data) => {
        const date = new Date(data.doc.content);
        console.log("Date:", date.toLocaleString());
      });
  };

  // This is the function that will be called when the button is clicked
  const handleUpdateMongoDoc = () => {
    console.log("update mongo doc");
    fetch("/api/update-mongo-doc")
      .then((response) => response.json())
      .then((data) => {
        const date = new Date(data.doc.value.content);
        console.log("Date: ", date.toLocaleString());
      });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>
          <button onClick={handleGetMongoDoc}>Get Mongo Doc</button>
          <button onClick={handleUpdateMongoDoc}>Update Mongo Doc</button>
        </div>
      </div>
    </>
  );
}
